// 静态网站生成器
import type { DailyData, NewsArticle } from './types.js';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

class Builder {
  private docsDir: string;

  constructor() {
    this.docsDir = join(process.cwd(), 'docs');
  }

  // 生成完整的 HTML 页面
  generateHTML(data: DailyData): string {
    const date = new Date(data.date).toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      weekday: 'long',
    });

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Daily Report - ${date}</title>
    <style>
        ${this.getCSS()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🤖 AI Daily Report</h1>
            <p class="date">${date}</p>
        </header>

        <main>
            ${this.generateCategories(data.categories)}
        </main>

        <footer>
            <p>自动 generated by AI | <a href="archive/">历史归档</a></p>
        </footer>
    </div>
</body>
</html>`;
  }

  // 生成分类区块
  private generateCategories(categories: Record<string, NewsArticle[]>): string {
    const order = ['AI/ML', '前端开发', '后端/架构', '开源项目', '其他'];
    
    return order
      .filter(cat => categories[cat] && categories[cat].length > 0)
      .map(cat => this.generateCategorySection(cat, categories[cat]))
      .join('\n');
  }

  // 生成单个分类的 HTML
  private generateCategorySection(category: string, articles: NewsArticle[]): string {
    const emojiMap: Record<string, string> = {
      'AI/ML': '🧠',
      '前端开发': '🎨',
      '后端/架构': '⚙️',
      '开源项目': '📦',
      '其他': '📌',
    };

    return `
        <section class="category">
            <h2>${emojiMap[category] || '📄'} ${category}</h2>
            <div class="articles">
                ${articles.map(a => this.generateArticleCard(a)).join('\n')}
            </div>
        </section>`;
  }

  // 生成单篇文章卡片
  private generateArticleCard(article: NewsArticle): string {
    const title = article.translatedTitle || article.title;
    const domain = article.source.replace(/^www\./, '');

    return `
                <article class="article-card">
                    <h3><a href="${article.url}" target="_blank" rel="noopener">${title}</a></h3>
                    <p class="summary">${article.summary || '暂无摘要'}</p>
                    <div class="meta">
                        <span class="source">${domain}</span>
                        <span class="date">${new Date(article.publishedDate).toLocaleDateString('zh-CN')}</span>
                    </div>
                </article>`;
  }

  // CSS 样式
  private getCSS(): string {
    return `:root {
    --bg-color: #0d1117;
    --card-bg: #161b22;
    --text-color: #c9d1d9;
    --text-muted: #8b949e;
    --border-color: #30363d;
    --link-color: #58a6ff;
    --accent-color: #7ee787;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans SC', sans-serif;
    background: var(--bg-color);
    color: var(--text-color);
    line-height: 1.6;
}

.container {
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem 1rem;
}

header {
    text-align: center;
    padding: 2rem 0;
    border-bottom: 1px solid var(--border-color);
    margin-bottom: 2rem;
}

header h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
}

.date {
    color: var(--text-muted);
    font-size: 1.1rem;
}

.category {
    margin-bottom: 2.5rem;
}

.category h2 {
    font-size: 1.5rem;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid var(--border-color);
}

.articles {
    display: grid;
    gap: 1rem;
}

.article-card {
    background: var(--card-bg);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    padding: 1.25rem;
    transition: transform 0.2s, border-color 0.2s;
}

.article-card:hover {
    transform: translateY(-2px);
    border-color: var(--link-color);
}

.article-card h3 {
    font-size: 1.1rem;
    margin-bottom: 0.75rem;
}

.article-card h3 a {
    color: var(--link-color);
    text-decoration: none;
}

.article-card h3 a:hover {
    text-decoration: underline;
}

.summary {
    color: var(--text-muted);
    font-size: 0.95rem;
    margin-bottom: 0.75rem;
    line-height: 1.6;
}

.meta {
    display: flex;
    gap: 1rem;
    font-size: 0.85rem;
    color: var(--text-muted);
}

.source {
    background: var(--bg-color);
    padding: 0.2rem 0.6rem;
    border-radius: 4px;
}

footer {
    text-align: center;
    padding: 2rem;
    margin-top: 2rem;
    border-top: 1px solid var(--border-color);
    color: var(--text-muted);
}

footer a {
    color: var(--link-color);
}

@media (max-width: 600px) {
    header h1 {
        font-size: 1.8rem;
    }
    
    .article-card {
        padding: 1rem;
    }
}`;
  }

  // 保存页面
  build(data: DailyData): void {
    // 确保 docs 目录存在
    mkdirSync(this.docsDir, { recursive: true });
    mkdirSync(join(this.docsDir, 'archive'), { recursive: true });

    // 生成首页（最新日报）
    const html = this.generateHTML(data);
    const indexPath = join(this.docsDir, 'index.html');
    writeFileSync(indexPath, html);
    console.log(`📄 Generated: ${indexPath}`);

    // 保存归档版本
    const date = new Date(data.date).toISOString().split('T')[0];
    const archivePath = join(this.docsDir, 'archive', `${date}.html`);
    writeFileSync(archivePath, html);
    console.log(`📄 Archived: ${archivePath}`);

    // 生成归档索引页
    this.generateArchiveIndex();
  }

  // 生成归档列表页
  private generateArchiveIndex(): void {
    const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>历史归档 - AI Daily Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #0d1117;
            color: #c9d1d9;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
        }
        h1 { color: #58a6ff; }
        a { color: #7ee787; }
        ul { list-style: none; padding: 0; }
        li { margin: 0.5rem 0; padding: 0.5rem; background: #161b22; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>📚 历史归档</h1>
    <p><a href="../">← 返回首页</a></p>
    <ul>
        <li><a href="../index.html">最新日报</a></li>
    </ul>
</body>
</html>`;

    writeFileSync(join(this.docsDir, 'archive', 'index.html'), html);
  }
}

// 主函数
function main() {
  console.log('🏗️  Building static site...\n');

  // 读取处理后的数据
  const dataPath = join(process.cwd(), 'data', 'processed.json');
  const data: DailyData = JSON.parse(readFileSync(dataPath, 'utf-8'));

  const builder = new Builder();
  builder.build(data);

  console.log('\n✅ Build complete!');
  console.log('   Output: docs/');
}

main();